name: CI

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main

jobs:
  build:
    name: Code standards & build
    runs-on: ubuntu-latest
    timeout-minutes: 3
    env:
      # 避免 Node 20 弃用警告，让 Actions 使用 Node 24 运行
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    strategy:
      matrix:
        node-version: [25]

    steps:
      - name: "☁️ Checkout repository"
        uses: actions/checkout@v6

      - name: "📦 Install pnpm"
        uses: pnpm/action-setup@v5
        with:
          version: 10.32.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: "📦 Install dependencies"
        run: pnpm install

      - name: "🔎 Lint code"
        run: pnpm run lint

      - name: "📝 Checking code format"
        run: pnpm run format:check

      - name: "🚀 Build the project"
        run: pnpm run build
