name: Sync feeds

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:
  push:
    paths:
      - public/data/rss.txt


jobs:
  sync:
    name: build feeds.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run feeds-aggregator
        uses: chensoul/feeds-aggregator@main
        with:
          sources: public/data/rss.txt
          output: public/data/feeds.json
          avatar-dir: public/avatars

      - name: sync favicons to R2
        env:
          RCLONE_CONFIG_R2_TYPE: s3
          RCLONE_CONFIG_R2_PROVIDER: Cloudflare
          RCLONE_CONFIG_R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
        run: |
          curl -OfsS https://downloads.rclone.org/rclone-current-linux-amd64.zip && unzip -oq rclone-current-linux-amd64.zip && mv rclone-*-linux-amd64/rclone /usr/local/bin/ && chmod +x /usr/local/bin/rclone
          rclone sync public/avatars r2:cos/avatars -P
          rm -rf rclone-*

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet public/data/feeds.json || (
            git add . &&
            git commit -m "chore: sync feeds.json from RSS sources" &&
            git push
          )
