name: Sync Running data

on:
  schedule:
    - cron: "0 0/2 * * *"
  workflow_dispatch:

jobs:
  sync:
    name: sync running.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: download running.json
        run: |
          curl -fsSL "https://raw.githubusercontent.com/chensoul/chensoul/main/data/running.json" -o public/data/running.json

      - name: commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet public/data/running.json || (git add  public/data/running.json && git commit -m "chore: sync running.json" && git push)
